### ISSUE TITLE
Proposer le mod sur le steamworkshop

### ISSUE THREAD

**Issue by inrepublica** [Squalalah/Francais#12]
Est-il possible de le rendre disponible sur le steamworkshop?

**Comment by Squalalah** [comment]
Il est déjà disponible sur le workshop

http://softwareinc.coredumping.com/forum/index.php?topic=287.0

http://steamcommunity.com/sharedfiles/filedetails/?id=678091195

**Comment by inrepublica** [comment]
Autant pour moi! Par contre il manque une image de présentation. Quand on regarde la liste des mods, il ne s'affiche aucune image de présentation. Sinon un gros merci pour le boulot ;-)

**Comment by Squalalah** [comment]
L'image a été rajouté, je n'avais pas trouvé comment faire alors que c'était tout con ;)

Merci et bonne journée à toi !

**Comment by inrepublica** [comment]
Juste un petit conseil, ajouter FR ou French au début du nom sur le workshop et mettre un drapeau FR sur l'image afin de clairement l'identifier. Sinon c'est du tout bon ;-)

**Comment by Squalalah** [comment]
Bah, j'ai écrit [Officiel], un mot pour dire que c'est un mod de traduction
officiel (j'ai mon thread sur le forum), et le mot Officiel pour dire que
c'est en français xD

2016-05-13 13:41 GMT+02:00 clark17 notifications@github.com:
